### ISSUE TITLE
filtering an empty array

### ISSUE THREAD

**Issue by githubGabriela** [vguillou/poly-filter#1]
I am implementing an iron-list with a huge number of items.
I have server-side and client-side filtering for the same list. For the client-side I use poly-filter. 

The use case is that the user enters a string for the search in the input text.
Then the search is made server-side and an array with results is returned.   

I made a little video with the issue. 
https://www.youtube.com/watch?v=aaOLgOGBhds&feature=youtu.be  (please view from second 0 to 6, the rest of time is just me trying to stop the recording of the screen :) )

Initially I have an array of 1000 items, then I filter server-side and the array has 3 items.
Then I search again and from the server-side I have 0 results.

There seems to be a problem when passing an array of 0 to poly-filter.
It  doesn't update its returned array, as the list still contains 3 items instead of 0.

**Comment by vguillou** [comment]
Indeed !
The problem here is a simple JS problem, as an empty array is considered falsy.
I will fix this within 24 hours and create a new release.
Thanks for reporting this issue. :-)

**Comment by vguillou** [comment]
Closed with the v1.2.1 release.
