### ISSUE TITLE
update filteredArray if the initial array has been changed

### ISSUE THREAD

**Issue by githubGabriela** [vguillou/poly-filter#2]
Hey vguillou,

Thank you for the release, the filtering it's working perfectly!
I have a small bug when adding a new item on the list.

As you can see in the screenshot, I have a list of 1414 items.  Then, by pressing the Add button I add another item to the list.
The problem is that filteredElements (the filtered array returned by poly-filter) still has 1414 items. 
Please watch the initial array and if the lenght changes update the array.

Thank you very much for your quick replies!! 

![capture d ecran 2016-03-04 a 16 32 20](https://cloud.githubusercontent.com/assets/10567659/13531422/c3c33e18-e226-11e5-83bb-8b23fabbf18b.png)

**Comment by vguillou** [comment]
Are you using Polymer's `push` method to add your new item to the `array-to-filter` ?
Like this for example :

```
this.push('myArrayToFilter', myNewItem);
```

(If you need more info, you can take a look at Polymer's array mutation API here :
https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-mutation)

**Comment by githubGabriela** [comment]
Hello,

I am using this.splice().  This is not the issue, the array is updating otherwise my list wouldn't update in the view with the added items.

I debugged poly-filter and the watchers are triggered only when a filter is passed for the array.  But when only the array is changed (by adding, removing items) no observer is triggered.  
I've added an observer in poly-filter that watches the arrayToFilter.splices. The observer was triggered when the size of the array changed. In the observer I've set the filtered array to the changed array  with this method     this._setFilteredArray(this.arrayToFilter); Here the arrayToFilter had 1415 items.

 The problem is that the returned array with filtered elements in my view still has 1414 and not 1415 as it should.

**Comment by vguillou** [comment]
Thanks, I've been able to reproduce.
A fix should come in the next couple of days.

**Comment by githubGabriela** [comment]
Thank you!

**Comment by vguillou** [comment]
The fix is included in the new [v1.2.2 release](https://github.com/vguillou/poly-filter/releases/tag/v1.2.2).
Thanks again for taking the time to report these issues. :+1:

**Comment by githubGabriela** [comment]
Thanks for the fix and the release, it works perfectly!
